// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "ai": {
    "conversation": {
      "emptyDescription": "Start a conversation to see messages here",
      "emptyTitle": "No messages yet"
    },
    "errors": {
      "auth": {
        "message": "Your key was rejected. Check your keys in Settings.",
        "title": "Connection needs attention"
      },
      "badRequest": {
        "message": "The request was invalid.",
        "title": "Couldn't send that"
      },
      "capability": {
        "fileTitle": "File attachments aren't supported",
        "imageTitle": "Image attachments aren't supported",
        "message": "This model doesn't support web search. Switch to a model that supports web search and try again.",
        "structuredTitle": "Structured output isn't supported",
        "webSearchTitle": "Web search isn't supported"
      },
      "entitlement": {
        "message": "Your gateway account can't use this model. Try a free-tier model or add credits.",
        "modelMessage": "{{model}} isn't included in your plan. Your gateway account can't use it — try a free-tier model or add credits.",
        "title": "Model not included in your plan"
      },
      "generic": {
        "message": "The request failed before finishing. Retrying usually works.",
        "title": "Something went wrong"
      },
      "rateLimited": {
        "message": "This model is rate-limited on your plan. Wait a few seconds and retry, or switch to another model.",
        "modelMessage": "{{model}} is rate-limited on your plan. Wait a few seconds and retry, or switch to another model.",
        "title": "AI is busy right now"
      },
      "retired": {
        "message": "This model was retired from the gateway. Pick a current model above and retry.",
        "title": "Model no longer available"
      },
      "substituted": {
        "message": "The gateway answered with a different model than the one you picked. Nothing was presented as working — retry, or switch to a model your plan includes.",
        "title": "Wrong model served"
      }
    },
    "gatewayKeyPrompt": {
      "description": "Add your AI Gateway key in Settings to unlock models.",
      "openSettings": "Open Settings",
      "title": "AI Gateway key required"
    },
    "markdownTable": {
      "ariaLabel": "Scrollable table"
    },
    "message": {
      "branchPage": "{{current}} of {{total}}",
      "nextBranch": "Next branch",
      "previousBranch": "Previous branch"
    },
    "modelSelector": {
      "providerLogo": "{{provider}} logo",
      "title": "Model Selector"
    },
    "promptInput": {
      "addPhotosOrFiles": "Add photos or files",
      "placeholder": "What would you like to know?",
      "stop": "Stop",
      "submit": "Submit",
      "takeScreenshot": "Take screenshot",
      "uploadFiles": "Upload files"
    },
    "reasoning": {
      "thinking": "Thinking...",
      "thoughtBrief": "Thought for a few seconds",
      "thoughtFor_one": "Thought for {{count}} second",
      "thoughtFor_other": "Thought for {{count}} seconds"
    },
    "sources": {
      "used_one": "Used {{count}} source",
      "used_other": "Used {{count}} sources"
    }
  },
  "chat": {
    "announcement": {
      "openingChat": "Opening chat.",
      "openingChatFor": "Opening chat for {{concept}}."
    },
    "assistant": {
      "branchPage": "{{current}} of {{total}}",
      "copied": "Copied!",
      "copyMessage": "Copy message",
      "nextVersion": "Next version",
      "previousVersion": "Previous version",
      "regenerateResponse": "Regenerate response"
    },
    "clearHistory": {
      "cancel": "Cancel",
      "clearFailed": "Couldn't clear chat history",
      "cleared": "Chat history cleared",
      "clearing": "Clearing...",
      "confirm": "Clear History",
      "description": "Are you sure you want to clear all chat messages in this notebook?",
      "title": "Clear Chat History"
    },
    "composer": {
      "attachPhoto": "Attach photo",
      "attachmentAlt": "Attachment",
      "imageAlt": "Image",
      "noModelsFound": "No models found",
      "placeholder": "Type a message...",
      "removeAttachment": "Remove attachment",
      "searchPlaceholder": "Search models...",
      "selectModelTitle": "Select Model",
      "sendMessage": "Send message",
      "stopResponse": "Stop response"
    },
    "empty": {
      "blankCanvas": "Start with a blank canvas",
      "welcomeDescription": "Ask questions or generate study materials based on your added sources.\n\nUse the chat composer below to get started.",
      "welcomeTitle": "Welcome to your notebook: \"{{title}}\""
    },
    "errorCard": {
      "addCredits": "Add credits",
      "openSettings": "Open settings",
      "retry": "Retry",
      "tip": "Tip: cheaper models are throttled less often."
    },
    "header": {
      "title": "Chat"
    },
    "locator": {
      "lines": "Lines {{value}}",
      "linesRange": "Lines {{start}}–{{end}}",
      "page": "Page {{number}}",
      "sheet": "Sheet \"{{name}}\"",
      "slide": "Slide {{number}}",
      "timestamp": "Timestamp",
      "visualRegion": "Visual region"
    },
    "message": {
      "copiedToClipboard": "Copied to clipboard"
    },
    "noEvidence": {
      "correctiveAction": "Suggested fix: import the file version or paste the source text, then ask again.",
      "degradedSection": "Sources that cannot be used as evidence",
      "description": {
        "below_threshold": "Retrieved passages did not match the question closely enough to answer from them.",
        "no_indexed_chunks": "No sources in this Notebook are indexed as evidence yet."
      },
      "title": "No usable evidence in this notebook",
      "unhelpfulReason": "nothing matched the question",
      "unhelpfulSection": "Sources without matching content"
    },
    "panel": {
      "gatewayBusy": "AI Gateway is busy — responses may fail. Waiting a bit and retrying usually works.",
      "gatewayKeyDescription": "An AI Gateway key is required to chat with your study assistant.",
      "notebookFallback": "Notebook"
    },
    "pending": {
      "thinking": "Thinking…",
      "waiting": "Waiting for response…"
    },
    "referencePopover": {
      "noExcerpt": "No excerpt is available for this reference.",
      "openSource": "Open source",
      "referencesAria": "References",
      "sourceUnavailable": "Source unavailable",
      "triggerAria": "Reference {{number}}: {{title}}",
      "unknownKind": "Source"
    },
    "userMessage": {
      "attachedImageAlt": "Attached image"
    }
  },
  "common": {
    "command": {
      "description": "Search for a command...",
      "title": "Command Palette"
    },
    "confirmDelete": {
      "cancel": "Cancel",
      "confirm": "Delete"
    },
    "dialog": {
      "close": "Close"
    },
    "errors": {
      "ai": {
        "embedding": {
          "notConfigured": "Embedding model is not configured. Add your Voyage API key in Settings."
        },
        "gateway": {
          "busy": "The AI service is busy right now. Please retry in a moment.",
          "connectionFailed": "AI Gateway connection failed",
          "creditsKeyMissing": "Add your AI Gateway key in Settings to view credits.",
          "creditsLoadFailed": "Could not load gateway credits.",
          "entitlement": "This model is not available on your plan. Try another model or add credits.",
          "keyRejected": "That gateway key was rejected. Check the key and try again.",
          "noModelAccess": "That gateway key has no model access on its plan.",
          "notConnected": "AI Gateway is not connected. Add your AI Gateway key in Settings.",
          "verifyFailed": "Could not verify the gateway key."
        },
        "indexing": {
          "embeddingCountMismatch": "Embedding count mismatch: expected {{expected}}, received {{received}}"
        },
        "model": {
          "capabilityUnsupported": "{{model}} doesn't support {{capability}}. Switch to a model that supports {{capability}} and try again.",
          "notSupported": "Model {{model}} is not supported.",
          "webSearchUnsupported": "Model {{model}} does not support web search."
        },
        "settings": {
          "legacyProviderKeys": "Per-provider keys were removed. Add your AI Gateway key in Settings."
        },
        "voyage": {
          "invalidResponse": "The embedding service returned an invalid response.",
          "keyRejected": "That Voyage API key was rejected. Check the key and try again.",
          "rateLimited": "The embedding service is rate-limiting requests. The job will retry automatically.",
          "requestFailed": "The embedding request was rejected.",
          "serverError": "The embedding service had a temporary problem. Please retry.",
          "unreachable": "Could not reach the embedding service. Check your connection and try again."
        }
      },
      "chat": {
        "message": {
          "empty": "Empty user message"
        }
      },
      "generation": {
        "problemCount": "Problem count must be between {{min}} and {{max}}.",
        "questionCount": "Question count must be between {{min}} and {{max}}.",
        "requestNotFound": "Generation request not found.",
        "sourceOrBrief": {
          "caseStudy": "Select a source or enter a brief for your case study.",
          "practiceProblems": "Select a source or enter a brief for your practice problems.",
          "studyGuide": "Select a source or enter a brief for your study guide."
        },
        "sourcesUnavailable": "Selected sources are unavailable or have no readable content. Update your selection and retry."
      },
      "notebooks": {
        "banner": {
          "fileEmpty": "Uploaded file is empty",
          "fileRequired": "File is required",
          "tooLarge": "Banner image exceeds maximum size of 2 MB",
          "unsupportedType": "Unsupported file type: {{fileType}}. Accepted: JPEG, PNG, WebP"
        },
        "notebook": {
          "notFound": "Notebook not found"
        }
      },
      "sources": {
        "artifact": {
          "invalidKey": "Invalid source artifact key",
          "invalidSize": "Invalid source artifact size",
          "sizeMismatch": "Source artifact size does not match upload metadata",
          "unavailable": "Source artifact is unavailable"
        },
        "create": {
          "fileEmpty": "Uploaded file is empty",
          "fileRequired": "File is required",
          "fileTooLarge": "File exceeds maximum size of {{maxBytes}} bytes",
          "textEmpty": "rawText must be non-empty",
          "textTooLarge": "rawText exceeds maximum size of {{maxBytes}} bytes",
          "urlTooLittleContent": "Page has too little content ({{length}} chars, need at least {{minLength}})"
        },
        "download": {
          "noFile": "Source has no downloadable file"
        },
        "extract": {
          "unsupportedFileType": "Unsupported file type: {{contentType}}"
        },
        "inspect": {
          "audioCorrupted": "The audio file appears to be corrupt or invalid.",
          "audioEmpty": "The audio file is empty.",
          "audioTooLarge": "The audio file ({{sizeMb}} MB) is too large. Maximum size is 500 MB.",
          "audioTooLong": "The audio duration ({{durationS}}s) is too long. Maximum is 4 hours.",
          "audioUnsupported": "Unsupported audio format ({{hint}}). Use MP3, WAV, M4A, AAC, WebM, or OGG.",
          "epubEmpty": "The ebook file is empty.",
          "epubInvalid": "The ebook file appears to be corrupt or invalid.",
          "epubTooLarge": "The ebook file ({{sizeMb}} MB) is too large. Maximum size is 200 MB.",
          "epubTooManyChapters": "The ebook has too many chapters ({{count}}). Maximum is {{max}}.",
          "epubUnsupported": "Unsupported ebook format ({{hint}}). Use .epub.",
          "imageCorrupted": "The image file appears to be corrupt or invalid.",
          "imageEmpty": "The image file is empty.",
          "imageTooLarge": "The image ({{sizeMb}} MB) is too large. Maximum size is 20 MB.",
          "imageTooManyPixels": "The image dimensions ({{width}}×{{height}}) are too large. Maximum is 40 megapixels.",
          "imageUnsupported": "Unsupported image format ({{hint}}). Use PNG, JPEG, or WebP.",
          "pptxCorrupted": "The presentation file appears to be corrupt or invalid.",
          "pptxEmpty": "The presentation file is empty.",
          "pptxLegacy": "Legacy .ppt files are not supported. Save the file as .pptx and try again.",
          "pptxTooLarge": "The presentation file ({{sizeMb}} MB) is too large. Maximum size is 200 MB.",
          "pptxTooManySlides": "The presentation has too many slides ({{count}}). Maximum is {{max}}.",
          "pptxUnsupported": "Unsupported presentation format ({{hint}}). Use .pptx.",
          "tabularCorrupted": "The data file appears to be corrupt or invalid.",
          "tabularEmpty": "The data file is empty.",
          "tabularTooLarge": "The data file ({{sizeMb}} MB) is too large. Maximum size is 100 MB.",
          "videoCorrupted": "The video file appears to be corrupt or invalid.",
          "videoEmpty": "The video file is empty.",
          "videoTooLarge": "The video file ({{sizeMb}} MB) is too large. Maximum size is 1 GB.",
          "videoTooLong": "The video duration ({{durationS}}s) is too long. Maximum is 4 hours.",
          "videoUnsupported": "Unsupported video format ({{hint}}). Use MP4, WebM, MOV, or MKV."
        },
        "parse": {
          "crawlFailed": "We couldn't fetch this webpage. Please try again.",
          "epubCorrupted": "The ebook file appears to be corrupt or invalid.",
          "pptxCorrupted": "The presentation file appears to be corrupt or invalid.",
          "tabularCorrupted": "The data file appears to be corrupt or invalid.",
          "zipCorrupted": "The archive appears to be corrupt or invalid."
        },
        "processing": {
          "noArtifact": "Source has no processable original artifact"
        },
        "quality": {
          "boilerplate": "Most of this source repeats boilerplate text, so it cannot be used as evidence.",
          "navigation": "Most of this source is links or navigation, so it cannot be used as evidence.",
          "paywall": "This source is mostly a paywall or sign-in message, so it cannot be used as evidence.",
          "unknown": "This source did not yield usable reading material, so it cannot be used as evidence."
        },
        "source": {
          "notFound": "Source not found"
        },
        "speaker": {
          "emptyMap": "Speaker map must not be empty",
          "noCurrentVersion": "Source has no current version to update"
        },
        "transcript": {
          "empty": "Transcript text must not be empty",
          "parseFailed": "Failed to parse transcript segments from provided text"
        },
        "upload": {
          "alreadyFinalized": "Upload target has already been finalized",
          "alreadyFinalizing": "Upload target is already being finalized",
          "expired": "Upload target has expired",
          "filenameRequired": "A filename up to 500 characters is required",
          "incomplete": "Upload is incomplete or no longer available",
          "integrityFailed": "Upload integrity check failed",
          "notFound": "Upload target not found",
          "notebookMismatch": "Upload target does not belong to this notebook",
          "presignedRequired": "This upload target requires its presigned URL",
          "sha256Invalid": "sha256 must be a 64-character hexadecimal digest",
          "sizeMismatch": "Upload size does not match the upload target",
          "sizePositive": "Upload size must be a positive integer",
          "storeFailed": "Upload could not be stored",
          "targetUnavailable": "Upload target is no longer available",
          "tooLarge": "Upload exceeds maximum size of {{maxBytes}} bytes",
          "tooLargeGeneric": "Upload exceeds the maximum allowed size",
          "unsupportedType": "Unsupported file type: {{contentType}} ({{filename}})"
        },
        "web": {
          "contentTypeUnsupported": "Unsupported content-type: {{contentType}}",
          "credentialsNotAllowed": "URLs with embedded credentials are not allowed",
          "extractionFailed": "Could not extract main content from page",
          "fetchFailed": "Fetch failed: HTTP {{status}}",
          "fetchFailedReason": "Fetch failed: {{reason}}",
          "hostnameEmpty": "Invalid hostname: empty",
          "hostnameInvalid": "Invalid hostname: {{hostname}}",
          "notReaderable": "Page does not contain article-like content",
          "portNotAllowed": "Port {{port}} is not allowed. Allowed ports: {{allowedPorts}}",
          "privateAddress": "URL resolves to a private or restricted address: {{hostname}}",
          "protocolUnsupported": "Unsupported protocol: {{protocol}}",
          "redirectNoLocation": "Redirect (HTTP {{status}}) without a Location header",
          "responseTooLarge": "Response exceeded {{maxBytes}} bytes",
          "robotsDenied": "Fetch denied by robots.txt policy: {{url}}",
          "timeout": "Request timed out after {{ms}}ms",
          "tooManyRedirects": "Too many redirects (limit {{limit}})",
          "urlInvalid": "Invalid URL: {{url}}",
          "urlRequired": "URL is required",
          "urlTooLong": "URL exceeds maximum length of {{max}} characters"
        },
        "webSearch": {
          "unavailable": "Web search is unavailable right now. Please try again later."
        },
        "youtube": {
          "captionParseFailed": "Failed to parse user-provided caption: {{reason}}",
          "invalidUrl": "Invalid YouTube URL or video ID: \"{{url}}\"",
          "oauthCaptionFailed": "OAuth caption acquisition failed: {{reason}}",
          "oauthDownloadFailed": "Failed to download YouTube caption track {{captionId}} (HTTP {{status}}): {{reason}}",
          "oauthDownloadTokenRequired": "OAuth access token is required to download YouTube caption",
          "oauthListFailed": "Failed to list YouTube captions (HTTP {{status}}): {{reason}}",
          "oauthListTokenRequired": "OAuth access token is required to list YouTube captions"
        }
      },
      "storage": {
        "dev": {
          "fileNotFound": "File not found",
          "invalidSignature": "Invalid signature",
          "linkExpired": "Link expired"
        }
      },
      "studyMaterials": {
        "aiNotConfigured": "AI service is not configured",
        "caseStudy": {
          "analysisQuestionIdsUnique": "Case study analysis question IDs must be unique",
          "invalidContent": "Invalid case study content",
          "missingAnalysis": "Case study must include an analysis for each question",
          "mustBeFictional": "Case study scenarios must be fictional",
          "questionCountMismatch": "Case study question count does not match the request",
          "questionIdsUnique": "Case study question IDs must be unique",
          "sourceUnavailable": "Case study references an unselected or unavailable source",
          "unknownQuestion": "Case study analysis references an unknown question"
        },
        "contentMismatch": "Content does not match kind \"{{kind}}\"",
        "duplicateDeleted": "Cannot duplicate a deleted study material",
        "evaluation": {
          "capability": "{{modelName}} doesn't support answer evaluation. Switch to another model and try again.",
          "entitlement": "{{modelName}} is not available on your plan. Try another model or add credits.",
          "rateLimited": "The AI service is busy right now. Please retry in a moment.",
          "transient": "The AI service is temporarily unavailable. Please try again shortly."
        },
        "exportDeleted": "Cannot export a deleted study material",
        "exportOnlySlides": "Only slides can be exported as PowerPoint",
        "exportUnavailable": "Slides export is unavailable",
        "folderAlreadyDeleted": "Folder already deleted",
        "folderDeleteHasMaterials": "Cannot delete folder: please delete all study materials inside first",
        "folderInTrash": "Cannot move to a folder in Trash",
        "folderNameEmpty": "Folder name cannot be empty",
        "folderNotFound": "Folder not found",
        "folderNotInNotebook": "Folder does not belong to this notebook",
        "folderOwnParent": "Folder cannot be its own parent",
        "folderReparentCycle": "Cannot reparent folder under one of its descendants",
        "invalidKind": "Invalid study material kind: {{kind}}",
        "invalidModelOutput": "Invalid output format from model",
        "notPracticeProblems": "Study material is not a practice problems set",
        "onlyQuizzesShuffled": "Only quizzes can be shuffled",
        "practiceProblemNotFound": "Practice problem not found",
        "practiceProblems": {
          "countMismatch": "Practice problem count does not match the request",
          "invalidContent": "Invalid practice problems content",
          "problemIdsUnique": "Practice problem IDs must be unique",
          "sourceUnavailable": "Practice problems reference an unselected or unavailable source",
          "stepIdsUnique": "Worked step IDs must be unique within a problem"
        },
        "studyGuide": {
          "countMismatch": "Study guide section count does not match the request",
          "detailedRequiresExtras": "Detailed study guides require examples, misconceptions, and takeaways in each section",
          "invalidContent": "Invalid study guide content",
          "sectionIdsUnique": "Study guide section IDs must be unique",
          "sourceUnavailable": "Study guide references an unselected or unavailable source"
        },
        "studyMaterialNotFound": "Study material not found",
        "titleEmpty": "Title cannot be empty"
      },
      "validation": {
        "invalid": "Invalid value for {{field}}.",
        "invalidFormat": "Invalid format for {{field}}.",
        "invalidType": "Invalid value for {{field}}: expected {{expected}}.",
        "invalidValue": "Invalid value for {{field}}.",
        "tooBig": "Invalid value for {{field}}: must be at most {{maximum}}.",
        "tooSmall": "Invalid value for {{field}}: must be at least {{minimum}}."
      }
    },
    "iconPicker": {
      "ariaLabel": "Icons",
      "categories": {
        "communication": "Communication",
        "files": "Files",
        "media": "Media",
        "objects": "Objects",
        "popular": "Popular",
        "system": "System",
        "tech": "Tech"
      },
      "clearSearch": "Clear search",
      "noResults": "No icons found",
      "results": "Results",
      "scrollForMore": "Scroll down for more icons...",
      "searchPlaceholder": "Search for an icon",
      "selectIcon": "Select icon",
      "selectedIcon": "Selected icon: {{name}}",
      "tryAnother": "Try searching for another keyword"
    },
    "messageScroller": {
      "toEnd": "Scroll to end",
      "toStart": "Scroll to start"
    },
    "routeProgress": {
      "loading": "Loading page"
    },
    "settingsLink": {
      "ariaLabel": "Settings"
    },
    "spinner": {
      "loading": "Loading"
    }
  },
  "generation": {
    "actions": {
      "auto": "Auto",
      "autoDecides": "Auto (AI decides)",
      "back": "Back",
      "custom": "Custom",
      "generate": "Generate",
      "generateKind": "Generate {{kind}}",
      "generateNow": "Generate {{kind}} Now",
      "nextStep": "Next Step",
      "view": "View"
    },
    "caseStudy": {
      "conceptsPlaceholder": "e.g. Apply triage frameworks and compare efficiency vs. fairness perspectives...",
      "conceptsToApplyLabel": "Concepts to Apply",
      "customQuestionAria": "Custom question count",
      "discussionQuestionsLabel": "1. Discussion Questions",
      "instructionsPlaceholder": "Describe what topics or focus areas to include in this case study...",
      "perspective": {
        "compare": {
          "desc": "Contrast viewpoints sources support",
          "title": "Compare alternatives"
        },
        "single": {
          "desc": "One focused analysis",
          "title": "Single lens"
        }
      },
      "perspectiveLabel": "2. Perspective",
      "questionCount_one": "{{count}} Question",
      "questionCount_other": "{{count}} Questions"
    },
    "dialog": {
      "gatewayDescription": "An AI Gateway key is required to generate study materials.",
      "title": "Generate {{kind}}"
    },
    "errors": {
      "connectionClosed": "Connection closed before finishing.",
      "noRequestId": "No request ID returned from server",
      "timedOut": "Generation timed out waiting for the server. Please try again."
    },
    "fields": {
      "customInstructions": "Custom Instructions",
      "destinationFolder": "Destination Folder",
      "detailLevelStep2": "2. Detail Level",
      "detailLevelStep3": "3. Detail Level",
      "folder": "Folder",
      "instructions": "Instructions",
      "knowledgeSources": "Knowledge Sources",
      "knowledgeSourcesStep3": "3. Knowledge Sources",
      "sources": "Sources",
      "targetDifficulty": "1. Target Difficulty"
    },
    "flashcards": {
      "cardFormatLabel": "1. Card Format",
      "cardStyle": {
        "cloze": {
          "desc": "Sentence with missing word(s)",
          "title": "Fill-in-the-Blank"
        },
        "definition": {
          "desc": "Term → definition pairs",
          "title": "Definition"
        },
        "mixed": {
          "desc": "Combination of Q&A, Definitions, and Fill-in-the-Blank",
          "title": "Mixed"
        },
        "qa": {
          "desc": "Classic question → answer format",
          "title": "Q & A"
        }
      },
      "cardsLabel": "3. Cards",
      "countMax": "{{count}} Cards (Max {{max}})",
      "countMax_one": "{{count}} Card (Max {{max}})",
      "countMax_other": "{{count}} Cards (Max {{max}})",
      "count_one": "{{count}} Card",
      "count_other": "{{count}} Cards",
      "customCountAria": "Custom card count",
      "difficulty": {
        "easy": {
          "desc": "Simple definitions & recall",
          "title": "Basic"
        },
        "hard": {
          "desc": "Deep analysis & application",
          "title": "Advanced"
        },
        "medium": {
          "desc": "Conceptual understanding",
          "title": "Standard"
        }
      },
      "difficultyLabel": "2. Difficulty",
      "instructionsPlaceholder": "What topics should these flashcards cover?"
    },
    "kinds": {
      "case_study": "Case Study",
      "mind_map": "Mind Map",
      "practice_problems": "Practice Problems",
      "quiz": "Quiz",
      "roadmap": "Roadmap",
      "simple_flashcard": "Flashcards",
      "slides": "Slides",
      "study_guide": "Study Guide"
    },
    "knowledge": {
      "defaultEmptySources": "No sources in notebook. Material will generate using general knowledge.",
      "defaultPlaceholder": "What should this cover? Describe topics, focus areas, or tone...",
      "emptySources": "No sources in notebook. {{kind}} will generate using general knowledge.",
      "noneSelected": "None selected (General Knowledge)",
      "searchAriaLabel": "Search sources",
      "searchPlaceholder": "Search sources...",
      "selectAll": "Select all",
      "selectedCount": "{{count}} selected",
      "selectedCount_one": "{{count}} selected",
      "selectedCount_other": "{{count}} selected",
      "selected_one": "{{count}} source selected",
      "selected_other": "{{count}} sources selected"
    },
    "mindMap": {
      "colorGroups": {
        "grouped": {
          "desc": "Color related concepts by theme",
          "title": "Grouped colors"
        },
        "plain": {
          "desc": "Use the standard node appearance",
          "title": "Plain"
        }
      },
      "customCountAria": "Custom node count",
      "detail": {
        "basic": {
          "desc": "Key concepts and essential relationships",
          "title": "Basic"
        },
        "detailed": {
          "desc": "Richer labels and explanatory connections",
          "title": "Detailed"
        }
      },
      "instructionsPlaceholder": "What should this map explain? Describe the topic, question, or connections...",
      "mapSizeLabel": "1. Map Size",
      "nodeCountMax": "{{count}} nodes (max {{max}})",
      "nodeCountMax_one": "{{count}} node (max {{max}})",
      "nodeCountMax_other": "{{count}} nodes (max {{max}})",
      "nodeCount_one": "{{count}} node",
      "nodeCount_other": "{{count}} nodes",
      "visualGroupingLabel": "3. Visual Grouping"
    },
    "practice": {
      "difficulty": {
        "easy": {
          "desc": "Foundations & single steps",
          "title": "Warmup"
        },
        "hard": {
          "desc": "Multi-step & transfer",
          "title": "Challenge"
        },
        "medium": {
          "desc": "Balanced application",
          "title": "Standard"
        }
      },
      "instructionsPlaceholder": "Topics, skills, problem types (calculations, code reasoning, explanations)...",
      "problemCountMax": "{{count}} Problems (Max {{max}})",
      "problemCountMax_one": "{{count}} Problem (Max {{max}})",
      "problemCountMax_other": "{{count}} Problems (Max {{max}})",
      "problemCount_one": "{{count}} Problem",
      "problemCount_other": "{{count}} Problems",
      "problemsLabel": "2. Number of Problems"
    },
    "quiz": {
      "difficulty": {
        "easy": {
          "desc": "Basic recall & definitions",
          "title": "Warmup"
        },
        "hard": {
          "desc": "Deep reasoning & edge cases",
          "title": "Challenge"
        },
        "medium": {
          "desc": "Balanced application",
          "title": "Standard"
        }
      },
      "instructionsPlaceholder": "Provide specific focus areas, topics, or instructions for this quiz...",
      "questionCountMax": "{{count}} Questions (Max {{max}})",
      "questionCountMax_one": "{{count}} Question (Max {{max}})",
      "questionCountMax_other": "{{count}} Questions (Max {{max}})",
      "questionCount_one": "{{count}} Question",
      "questionCount_other": "{{count}} Questions",
      "questionPreset": "{{count}} Qs",
      "questionPreset_one": "{{count}} Q",
      "questionPreset_other": "{{count}} Qs",
      "questionsLabel": "2. Number of Questions"
    },
    "roadmap": {
      "autoLabel": "Auto (AI Decides optimal phases)",
      "detail": {
        "basic": {
          "desc": "Phase titles & milestones only",
          "title": "Basic"
        },
        "detailed": {
          "desc": "In-depth topics & learning objectives",
          "title": "Detailed"
        }
      },
      "instructionsPlaceholder": "What do you want to learn? Describe the topic, goal, or target skill...",
      "phaseCountMax": "{{count}} Phases (Max {{max}})",
      "phaseCountMax_one": "{{count}} Phase (Max {{max}})",
      "phaseCountMax_other": "{{count}} Phases (Max {{max}})",
      "phaseCount_one": "{{count}} Phase",
      "phaseCount_other": "{{count}} Phases",
      "phasesLabel": "1. Number of Phases"
    },
    "slides": {
      "countMax": "{{count}} Slides (Max {{max}})",
      "countMax_one": "{{count}} Slide (Max {{max}})",
      "countMax_other": "{{count}} Slides (Max {{max}})",
      "count_one": "{{count}} Slide",
      "count_other": "{{count}} Slides",
      "customCountAria": "Custom slide count",
      "detail": {
        "basic": {
          "desc": "Concise bullets",
          "title": "Basic"
        },
        "detailed": {
          "desc": "Rich bullets + body",
          "title": "Detailed"
        }
      },
      "instructionsPlaceholder": "What should this deck explain? Describe the topic, audience, or narrative arc...",
      "numberOfSlidesLabel": "1. Number of Slides",
      "themeTooltip": "{{title}}: {{desc}}",
      "themes": {
        "academic": {
          "desc": "Classic lecture style",
          "title": "Academic"
        },
        "dark": {
          "desc": "Slate deck, cyan accent",
          "title": "Dark"
        },
        "editorial": {
          "desc": "Warm paper, serif voice",
          "title": "Editorial"
        },
        "light": {
          "desc": "Bright, print-friendly",
          "title": "Light"
        },
        "technical": {
          "desc": "Deep navy, neon detail",
          "title": "Technical"
        },
        "warm": {
          "desc": "Bold ember energy",
          "title": "Warm"
        }
      },
      "visualThemeLabel": "2. Visual Theme"
    },
    "standard": {
      "briefLabel": "Brief instructions for {{kind}} (optional)",
      "briefPlaceholder": "Describe what topics or focus areas to include in this {{kind}}..."
    },
    "studyGuide": {
      "customSectionAria": "Custom section count",
      "format": {
        "detailed": {
          "desc": "Explanations, examples & takeaways",
          "title": "Detailed"
        },
        "revision": {
          "desc": "Essential concepts for quick review",
          "title": "Revision sheet"
        }
      },
      "formatLabel": "1. Format",
      "instructionsPlaceholder": "Describe what topics or focus areas to include in this study guide...",
      "sectionCount_one": "{{count}} Section",
      "sectionCount_other": "{{count}} Sections",
      "sectionsLabel": "2. Sections"
    },
    "toasts": {
      "cancelled": "Generation cancelled",
      "failed": "Failed to generate {{kind}}: {{message}}",
      "startFailed": "Generation failed: {{message}}",
      "success": "{{kind}} generated successfully!"
    },
    "wizard": {
      "nextHintFocus": "Configure focus areas next",
      "nextHintInstructions": "Configure custom instructions next",
      "nextHintKnowledge": "Configure knowledge sources & brief next",
      "stepAria": "Step {{step}}",
      "stepOfTwo": "Step {{step}} of 2",
      "title": "{{kind}} Setup"
    }
  },
  "notebooks": {
    "banner": {
      "add": "Add banner",
      "cancelEdits": "Cancel edits",
      "canvas": "Notebook banner",
      "change": "Change",
      "dragToReposition": "Drag to reposition",
      "editNotebook": "Edit notebook",
      "noImage": "No banner image set",
      "previewAlt": "Notebook Banner Preview",
      "previewRegion": "Notebook banner preview",
      "remove": "Remove banner",
      "removeBanner": "Remove Banner",
      "save": "Save",
      "saving": "Saving…",
      "titleAria": "Notebook title",
      "titlePlaceholder": "Notebook Title",
      "titleRequired": "Title is required",
      "untitledNotebook": "Untitled Notebook",
      "updateFailed": "Failed to update notebook",
      "updated": "Notebook updated",
      "upload": "Upload",
      "uploadHint": "Upload an image to customize your notebook",
      "uploadImage": "Upload Banner Image"
    },
    "description": {
      "addDetailed": "Add a detailed description for your notebook...",
      "ariaLabel": "Notebook description",
      "label": "Description",
      "less": "Less",
      "more": "More",
      "placeholder": "Describe what this notebook is for…"
    },
    "folders": {
      "create": "Create",
      "createFailed": "Failed to create folder",
      "created": "Folder \"{{name}}\" created",
      "newFolderPlaceholder": "New folder name...",
      "notebookRoot": "Notebook Root"
    },
    "library": {
      "breadcrumbAria": "Breadcrumb",
      "create": {
        "aria": "Create",
        "folder": "Folder",
        "folderDescription": "Group notebooks together",
        "label": "Create new",
        "notebook": "Notebook",
        "notebookDescription": "Start a blank notebook"
      },
      "dropToMove": "Drop here to move to {{target}}",
      "editAria": "Edit {{label}}",
      "emptyFolderDescription": "Drag notebooks here or use the + button to create one.",
      "emptyFolderTitle": "This folder is empty",
      "emptyLibraryDescription": "Use the + button to create your first notebook or folder.",
      "emptyLibraryTitle": "No notebooks yet",
      "folderCardAria_one": "{{name}}, {{count}} notebook",
      "folderCardAria_other": "{{name}}, {{count}} notebooks",
      "heroSubtitle": "Pick up where you left off, or start something fresh.",
      "heroTitle": "Make progress on what matters.",
      "library": "Library",
      "loadFailedDescription": "Something went wrong while loading your notebooks. Check your connection and try again.",
      "loadFailedTitle": "Couldn't load your library",
      "moveTo": "Move To {{target}}",
      "moving": "Moving {{name}}",
      "removeFolder": "Remove Folder",
      "rename": "Rename",
      "retry": "Retry",
      "sort": {
        "aria": "Sort library",
        "createdAt": "Date created",
        "createdAtDescription": "Recently created first",
        "name": "Name",
        "nameDescription": "Alphabetical order",
        "updatedAt": "Last modified",
        "updatedAtDescription": "Recently changed first"
      },
      "toasts": {
        "folderCreateFailed": "Failed to create folder",
        "folderRemoveFailed": "Failed to remove folder",
        "folderUpdateFailed": "Failed to update folder",
        "notebookCreateFailed": "Failed to create notebook",
        "notebookRemoveFailed": "Failed to delete notebook",
        "notebookUpdateFailed": "Failed to update notebook"
      },
      "untitledFolder": "Untitled folder",
      "untitledNotebook": "Untitled notebook"
    },
    "notebook": {
      "editTitle": "Edit notebook title",
      "renameFailed": "Failed to rename notebook",
      "renamed": "Notebook renamed"
    },
    "panels": {
      "addSource": "Add source",
      "backToMaterial": "Back to Material",
      "chat": "Chat",
      "collapseSources": "Collapse sources",
      "collapseStudio": "Collapse studio",
      "expandSources": "Expand sources",
      "expandStudio": "Expand studio",
      "sections": "Notebook sections",
      "sources": "Sources",
      "studio": "Studio"
    },
    "resources": {
      "basedOnBrief": "based on brief",
      "basedOnSources_one": "based on {{count}} source",
      "basedOnSources_other": "based on {{count}} sources",
      "processingSources": "processing sources"
    },
    "settings": {
      "ariaLabel": "Notebook settings",
      "cancel": "Cancel",
      "clearChat": "Clear chat",
      "delete": "Delete notebook",
      "deleteConfirm": "Permanently delete “{{title}}” and all associated sources and notes?",
      "deleteFailed": "Failed to delete notebook",
      "deleted": "Notebook deleted",
      "deleting": "Deleting…",
      "description": "Edit or manage this notebook.",
      "edit": "Edit notebook",
      "thisNotebook": "this notebook",
      "title": "Notebook"
    },
    "sources": {
      "noSources": "No sources yet. Add a source first to generate a study material."
    },
    "studio": {
      "cancelGeneration": "Cancel generation",
      "dismiss": "Dismiss",
      "dismissError": "Dismiss error",
      "failedToGenerate": "Failed to generate {{kind}}",
      "generating": "Generating {{kind}}...",
      "generationFailed": "Generation failed",
      "resources": {
        "caseStudy": "Case Study",
        "flashcards": "Flashcards",
        "mindMap": "Mind Map",
        "practiceProblems": "Practice Problems",
        "quiz": "Quiz",
        "roadmap": "Roadmap",
        "slides": "Slides",
        "studyGuide": "Study Guide"
      },
      "tooltipGenerating": "{{label}} (Generating...)"
    },
    "upload": {
      "browse": "Browse files",
      "browseOrDrop": "Click to browse or drag & drop image",
      "description": "Select an image file from your computer. You can drag & zoom it directly on the banner canvas afterwards.",
      "formats": "JPG, PNG, WebP up to 2MB",
      "inputAria": "Upload notebook banner image",
      "title": "Upload Banner Image",
      "tooLarge": "Image is too large ({{size}}MB). Max 2MB.",
      "unsupportedFormat": "Unsupported image format ({{type}}). Use JPG, PNG, or WebP."
    },
    "viewer": {
      "goBack": "Go back",
      "loadFailed": "Failed to load study material",
      "select": "Select a study material to view its contents"
    }
  },
  "settings": {
    "appearance": {
      "description": "Choose how Memsystems looks. Theme sets the palette, color scheme sets light or dark.",
      "title": "Appearance"
    },
    "embeddings": {
      "apiKey": {
        "confirmRemove": "Confirm Remove",
        "hide": "Hide Voyage key",
        "label": "Voyage API Key",
        "placeholder": "Paste your Voyage AI key…",
        "remove": "Remove",
        "removeConfirm": "Removing your key stops source retrieval from working. Click again to confirm.",
        "removing": "Removing…",
        "replace": "Replace",
        "save": "Save Key",
        "saved": "Saved",
        "saving": "Saving…",
        "show": "Show Voyage key"
      },
      "description": {
        "checking": "Checking embedding provider status…",
        "connected": "Your Voyage AI key powers retrieval across all notebooks.",
        "missing": "Add your Voyage AI key below to power source retrieval."
      },
      "modelInfo": "Model: {{model}} · {{dimensions}} dimensions",
      "reembed": {
        "action": "Re-embed All Sources",
        "actionRunning": "Queueing…",
        "hint": "Queues background re-indexing for every source.",
        "title": "Re-embedding"
      },
      "status": {
        "checking": "Checking",
        "connected": "Connected",
        "notConnected": "Not connected"
      },
      "title": "Embeddings",
      "toast": {
        "reembedFailed": "Could not queue re-embedding",
        "reembedQueued": "Re-indexing queued for {{count}} sources",
        "removeFailed": "Could not remove this key",
        "removed": "Voyage key removed",
        "requestFailed": "The request failed",
        "saveFailed": "Could not save this key",
        "saved": "Voyage key saved"
      },
      "whatIsIt": "What is Voyage AI?"
    },
    "gateway": {
      "apiKey": {
        "confirmRemove": "Confirm Remove",
        "hide": "Hide gateway key",
        "label": "Gateway API Key",
        "placeholder": "Paste your Vercel AI Gateway key…",
        "remove": "Remove",
        "removeConfirm": "Removing your key disconnects every model. Click again to confirm.",
        "removing": "Removing…",
        "replace": "Replace",
        "save": "Save Key",
        "saved": "Saved",
        "saving": "Saving…",
        "show": "Show gateway key"
      },
      "description": {
        "checkFailed": "Failed to check connection",
        "checking": "Checking gateway status…",
        "connected": "Your Vercel AI Gateway key connects models across all notebooks.",
        "missing": "Add your AI Gateway key below to connect every model."
      },
      "lastChecked": "Last checked {{date}}",
      "refresh": {
        "action": "Refresh Models",
        "refreshing": "Refreshing Models…"
      },
      "refreshHint": "Refreshes automatically every 6 hours.",
      "stats": {
        "balance": "Balance (Credits)",
        "models": "Models",
        "used": "Credits Used"
      },
      "status": {
        "checking": "Checking",
        "connected": "Connected",
        "degraded": "Degraded",
        "notConnected": "Not connected"
      },
      "title": "AI Gateway",
      "toast": {
        "modelsRefreshed": "Model list refreshed",
        "refreshFailed": "Could not refresh the model list",
        "removeFailed": "Could not remove this key",
        "removed": "Gateway key removed",
        "saveFailed": "Could not save this key",
        "saved": "Gateway key saved"
      },
      "whatIsIt": "What is the gateway?"
    },
    "language": {
      "description": "Choose the language used across the app.",
      "title": "Language"
    },
    "page": {
      "title": "Settings"
    }
  },
  "sourceRenderers": {
    "articleViewer": {
      "noContent": "No article content available."
    },
    "audioPlayer": {
      "audioRecording": "Audio Recording",
      "cycleSpeed": "Click to cycle speed (0.75x, 1x, 1.25x, 1.5x, 2x)",
      "loadingStream": "Loading audio stream…",
      "mute": "Mute",
      "pause": "Pause",
      "play": "Play",
      "seekTime": "Seek time",
      "skipBackwardAria": "Skip backward 10 seconds",
      "skipBackwardTitle": "Skip backward 10s",
      "skipForwardAria": "Skip forward 10 seconds",
      "skipForwardTitle": "Skip forward 10s",
      "streamUnavailable": "Audio stream unavailable",
      "summary_one": "{{count}} segment · {{words}} words",
      "summary_other": "{{count}} segments · {{words}} words",
      "unmute": "Unmute",
      "volume": "Volume"
    },
    "audioSegment": {
      "cancelRename": "Cancel rename",
      "renameSpeakerAria": "Rename speaker",
      "renameSpeakerTitle": "Click to rename speaker",
      "renamed": "Renamed speaker to \"{{name}}\"",
      "saveSpeakerName": "Save speaker name",
      "seekAudioTitle": "Seek audio to this timestamp"
    },
    "audioTranscript": {
      "aiTranscription": "AI Transcription",
      "noSegments": "No transcript segments available for this audio file.",
      "noSegmentsMatch": "No transcript segments match \"{{query}}\".",
      "searchAria": "Search transcript text or speaker",
      "searchPlaceholder": "Search transcript text or speaker…"
    },
    "common": {
      "clearSearch": "Clear search"
    },
    "imageNote": {
      "formula": "Formula",
      "heading": "Heading",
      "regionLabel": "Region #{{ordinal}}",
      "visualDescription": "Visual Description"
    },
    "imageNotesPanel": {
      "aiVisionAnalysis": "AI Vision Analysis",
      "extractedNotes": "Extracted Notes",
      "noContent": "No extracted text or visual analysis available for this image.",
      "notice": "Notice"
    },
    "imagePreview": {
      "imageLoadFailed": "The original image could not be loaded directly.",
      "imagePreviewUnavailable": "Image preview unavailable",
      "loadingImage": "Loading image…"
    },
    "imageRegion": {
      "ariaLabel": "Region #{{ordinal}}: {{kind}}"
    },
    "imageToolbar": {
      "image": "Image",
      "imageDocument": "Image Document",
      "imageOnlyTitle": "Image Only",
      "notes": "Notes",
      "notesOnlyTitle": "Notes Only",
      "split": "Split",
      "splitViewTitle": "Split View",
      "visualRegions_one": "{{count}} visual region",
      "visualRegions_other": "{{count}} visual regions"
    },
    "imageViewer": {
      "partialTranscriptionWarning": "Some content in this image could not be fully transcribed."
    },
    "imageZoom": {
      "hideRegionHighlights": "Hide Region Highlights",
      "resetZoom": "Reset Zoom (100%)",
      "showRegionHighlights": "Show Region Highlights",
      "zoomIn": "Zoom In",
      "zoomOut": "Zoom Out"
    },
    "markdownViewer": {
      "noContent": "No text content available."
    },
    "plainTextViewer": {
      "noContent": "No text content available."
    },
    "pptxHeader": {
      "presentation": "Presentation",
      "slideCount_one": "{{count}} slide",
      "slideCount_other": "{{count}} slides"
    },
    "pptxSearch": {
      "clearSearch": "Clear search",
      "searchAria": "Search slides",
      "searchPlaceholder": "Search slides…"
    },
    "pptxSegmentList": {
      "noSegmentsMatch": "No segments match \"{{query}}\".",
      "segmentBadge": "Slide {{number}} · #{{ordinal}}",
      "segmentCount_one": "{{count}} segment",
      "segmentCount_other": "{{count}} segments",
      "title": "Slide Segments"
    },
    "pptxSlideContent": {
      "blockCount_one": "{{count}} block",
      "blockCount_other": "{{count}} blocks",
      "noContentMatch": "No content matches \"{{query}}\" on this slide.",
      "slideLabel": "Slide {{number}}",
      "slideRef": "[Slide {{number}}]"
    },
    "pptxSlideNavigator": {
      "slides": "Slides"
    },
    "pptxViewer": {
      "noContent": "This presentation has no extractable slide content.",
      "noSlidesExtracted": "No slides extracted"
    },
    "tabularViewer": {
      "columnSummary": "{{rows}} rows • {{cols}} columns",
      "defaultDatasetName": "Dataset",
      "filterPlaceholder": "Filter table rows...",
      "locator": "Locator: {{range}}",
      "nextPage": "Next page",
      "noMatchingRows": "No matching rows found.",
      "pagination": "Showing {{start}}–{{end}} of {{total}} rows",
      "previousPage": "Previous page"
    },
    "videoPlayer": {
      "loadingVideo": "Loading video…",
      "streamUnavailable": "Video stream unavailable",
      "videoLoadFailed": "The source file could not be loaded."
    },
    "videoTranscript": {
      "addOrReplaceTitle": "Add or replace transcripts",
      "addReplace": "Add / Replace",
      "addTranscripts": "Add Transcripts",
      "noTranscriptAttached": "No transcript attached to this video",
      "noTranscripts": "No Transcripts",
      "noTranscriptsDescription": "Add or paste a transcript to follow along with synchronized timestamps and search.",
      "seekVideoTitle": "Seek video to this timestamp",
      "transcript": "Transcript",
      "visualNote": "Visual Note"
    }
  },
  "sources": {
    "addSourceDialog": {
      "description": "Search the web or bring in your own material.",
      "title": "Add Knowledge Sources"
    },
    "api": {
      "addSourceFailed": "Failed to add source ({{status}})",
      "cancelSourceFailed": "Failed to cancel source ({{status}})",
      "finalizeUploadFailed": "Failed to finalize upload ({{status}})",
      "prepareUploadFailed": "Failed to prepare upload ({{status}})",
      "retrySourceFailed": "Failed to retry source ({{status}})",
      "uploadFileFailed": "Failed to upload file ({{status}})"
    },
    "fileUploadMode": {
      "copiedText": "Copied Text",
      "dropFiles": "Drop your files here",
      "supportedFormats": "Supports PDF, DOCX, TXT, Markdown, Images, Audio, Video, Presentations, eBooks, LaTeX, and BibTeX.",
      "unsupportedFileType": "Unsupported file type. Use PDF, DOCX, TXT, Markdown, Images, Audio, Video, PPTX, EPUB, TeX, or BibTeX files.",
      "uploadFile": "Upload a file",
      "uploadFiles": "Upload Files",
      "uploading": "Uploading file...",
      "websites": "Websites"
    },
    "menu": {
      "orAddDirectly": "Or add a source directly",
      "sourcesUsed": "Sources used"
    },
    "panel": {
      "addSourcesPrompt": "Add sources (PDF, Web, Text) to inform your AI study assistant",
      "deleteDescription": "Are you sure you want to delete \"{{title}}\"?",
      "deleteTitle": "Delete Source"
    },
    "pendingUpload": {
      "cancelProcessing": "Cancel source processing",
      "cancelled": "Cancelled",
      "dismiss": "Dismiss",
      "dismissStatus": "Dismiss source status",
      "processingFailed": "Source processing failed",
      "saving": "Saving source…"
    },
    "processing": {
      "analyzingVisuals": "Analyzing visuals…",
      "cancelled": "Cancelled",
      "degraded": "Degraded",
      "extracting": "Extracting content…",
      "failed": "Processing failed",
      "indexing": "Indexing source…",
      "processing": "Processing source…",
      "queued": "Queued for processing",
      "ready": "Ready",
      "transcribingAudio": "Transcribing audio…",
      "transcribingVideo": "Transcribing video…",
      "uploading": "Uploading original…"
    },
    "quality": {
      "action": {
        "boilerplate": "Import the file version or paste the text into a new source.",
        "default": "Import the file version or paste the text into a new source.",
        "navigation": "Import the file version or paste the text into a new source.",
        "paywall": "Paste the text you can access or import the file version."
      },
      "degradedTitle": "This source has no usable content",
      "reason": {
        "boilerplate": "Most of this source repeats the same boilerplate instead of unique material.",
        "navigation": "Most of this source is links, navigation, or a table of contents.",
        "paywall": "This source is mostly a paywall or sign-in message.",
        "unknown": "This source did not yield usable reading material."
      }
    },
    "reader": {
      "backToSources": "Back to sources",
      "close": "Close",
      "downloadFailed": "Download failed",
      "downloadFile": "Download File",
      "downloadLinkFailed": "Failed to retrieve download link",
      "downloadStarted": "Download started",
      "exitFullscreen": "Exit Fullscreen (Esc)",
      "failedToLoad": "Failed to load document",
      "fullscreenMode": "Fullscreen Mode",
      "loadFailedDescription": "Unable to load source details. Please try again.",
      "moreActions": "More actions",
      "notAvailable": "This source is not available for reading.",
      "openOriginalWebpage": "Open original webpage",
      "openWebpage": "Open Webpage",
      "processingWillBeAvailable": "This source will become available here when processing finishes."
    },
    "skeletons": {
      "audioStartTime": "0:00",
      "image": "Image",
      "notes": "Notes",
      "slideLabel": "Slide {{number}}",
      "split": "Split"
    },
    "sourceRow": {
      "delete": "Delete source",
      "retryProcessing": "Retry source processing"
    },
    "sourcesList": {
      "emptyDescription": "Add material to ground your chats and study materials.",
      "emptyTitle": "No sources yet",
      "failedToLoad": "Failed to load sources"
    },
    "states": {
      "backToSources": "Back to Sources"
    },
    "stats": {
      "linesAndChars_one": "{{count}} line · {{chars}} chars",
      "linesAndChars_other": "{{count}} lines · {{chars}} chars"
    },
    "textMode": {
      "add": "Add Text Source",
      "adding": "Adding text...",
      "back": "Back",
      "clear": "Clear",
      "content": "Content",
      "contentPlaceholder": "Paste your copied text here...",
      "title": "Title",
      "titlePlaceholder": "My Study Notes"
    },
    "toasts": {
      "audioAdded": "Audio source added",
      "audioUploadFailed": "Failed to upload audio",
      "bibtexAdded": "BibTeX source added",
      "bibtexUploadFailed": "Failed to upload BibTeX file",
      "ebookAdded": "eBook source added",
      "ebookUploadFailed": "Failed to upload eBook",
      "fileAdded": "File source added",
      "fileUploadFailed": "Failed to upload file",
      "imageAdded": "Image source added",
      "imageUploadFailed": "Failed to upload image",
      "latexAdded": "LaTeX source added",
      "latexUploadFailed": "Failed to upload LaTeX file",
      "pastedText": "Pasted text",
      "presentationAdded": "Presentation source added",
      "presentationUploadFailed": "Failed to upload presentation",
      "sourceProcessingCancelled": "Source processing cancelled",
      "sourceProcessingRestarted": "Source processing restarted",
      "sourceRemoved": "Source removed",
      "textAddFailed": "Failed to add text source",
      "textAdded": "Text source added",
      "urlAddFailed": "Failed to add URL source",
      "urlAdded": "URL source added",
      "videoAdded": "Video source added",
      "videoUploadFailed": "Failed to upload video",
      "youtubeAddFailed": "Failed to add YouTube video source",
      "youtubeAdded": "YouTube video source added"
    },
    "transcriptDialog": {
      "addSuccess_one": "Added transcript with {{count}} segment",
      "addSuccess_other": "Added transcript with {{count}} segments",
      "cancel": "Cancel",
      "clear": "Clear",
      "detected_one": "Detected: {{count}} segment",
      "detected_other": "Detected: {{count}} segments",
      "emptyError": "Please enter or upload transcript text",
      "fileLoaded": "Loaded \"{{name}}\"",
      "pasteLabel": "Paste Transcript or Subtitles",
      "placeholder": "(00:00) Introduction\n(00:04) First key topic\n(00:15) Practical steps\n\nOr YouTube transcript copy:\n0:04\nFirst section speech text\n0:15\nSecond section speech text",
      "save": "Save Transcripts",
      "saveFailed": "Failed to save transcript",
      "saving": "Saving…",
      "title": "Add Transcripts to Video",
      "uploadButton": "Upload .srt / .vtt / .txt"
    },
    "urlMode": {
      "addArxiv": "Add arXiv Paper Source",
      "addDoi": "Add DOI Academic Source",
      "addWebsite": "Add Website Source",
      "addYouTube": "Add YouTube Video Source",
      "addingArxiv": "Acquiring arXiv paper...",
      "addingDoi": "Resolving DOI...",
      "addingWebsite": "Extracting website...",
      "addingYouTube": "Adding YouTube video...",
      "advancedOptions": "Custom Captions & OAuth Options",
      "arxivBadge": "arXiv Paper",
      "arxivInfo": "Imports paper metadata and PDF full-text from arXiv.",
      "back": "Back",
      "captionFileLabel": "Upload Subtitles / Captions (.srt, .vtt, .txt, .json)",
      "captionLabel": "Or Paste Subtitle / Transcript Text",
      "captionPlaceholder": "00:00:01.000 --> 00:00:04.000\nSpeaker: Text content...",
      "clear": "Clear",
      "doiBadge": "DOI Identifier",
      "doiInfo": "Resolves citation metadata, BibTeX, and accessible open-access articles.",
      "oauthLabel": "Google OAuth Access Token (Optional, for private videos)",
      "placeholderArxiv": "e.g. 2301.12345 or https://arxiv.org/abs/2301.12345",
      "placeholderDoi": "e.g. 10.1000/182 or https://doi.org/10.1000/182",
      "placeholderGeneric": "https://example.com/article, YouTube URL, arXiv ID, or DOI...",
      "placeholderYouTube": "https://youtube.com/watch?v=... or https://youtu.be/...",
      "titleLabel": "Title (Optional)",
      "titlePlaceholderArxiv": "Defaults to paper title",
      "titlePlaceholderDoi": "Defaults to publication title",
      "titlePlaceholderGeneric": "Defaults to webpage title",
      "titlePlaceholderYouTube": "Defaults to video title",
      "urlLabel": "URL or Academic Identifier",
      "youtubeBadge": "YouTube Video"
    },
    "webSearch": {
      "clearFailed": "Couldn't clear these results. Try again.",
      "clearResults": "Clear results",
      "clearing": "Clearing…",
      "deselectAll": "Deselect all",
      "emptyDescription": "Try a more specific topic, add a date, or name the kind of source you need.",
      "emptyTitle": "No useful sources found",
      "errorTitle": "Web search failed",
      "failedTitle": "Results weren't cleared",
      "importFailed": "Import failed",
      "inputLabel": "What would you like to research?",
      "inputPlaceholder": "What would you like to research?",
      "intro": "Describe what you want to research. You can review every result before adding it.",
      "limitReached": "Source limit reached",
      "limitReachedDescription": "Remove a source before searching for more sources to add.",
      "resultsCleared": "Search results cleared",
      "retryFailed": "Retry failed",
      "search": "Search",
      "searchFailed": "Web search failed",
      "searching": "Searching",
      "searchingHint": "Searching for reliable sources. You can close this dialog and return later.",
      "selectAll": "Select all",
      "title": "Find sources on the web"
    },
    "webSearchResults": {
      "addError": "Could not add: {{error}}",
      "addSelected": "Add selected",
      "added": "Added",
      "addedAndFailed": "{{added}} added · {{failed}} failed",
      "addedCount": "{{count}} added",
      "addedCount_one": "{{count}} added",
      "addedCount_other": "{{count}} added",
      "adding": "Adding",
      "fetchFailed": "source could not be fetched",
      "limitReached": "Not added because the source limit was reached",
      "opensNewTab": "Opens in a new tab",
      "retryFailed": "Retry failed",
      "selectLabel": "Select {{title}}",
      "selectedCount": "{{count}} selected",
      "selectedCount_one": "{{count}} selected",
      "selectedCount_other": "{{count}} selected",
      "showLess": "Show less",
      "showMore": "Show more",
      "sourceFound_one": "{{count}} source found",
      "sourceFound_other": "{{count}} sources found",
      "sourceSlotsAvailable_one": "{{count}} source slot available",
      "sourceSlotsAvailable_other": "{{count}} source slots available"
    }
  },
  "theme": {
    "descriptions": {
      "default": "Neutral — what you see today",
      "dune": "Warm sand, soft and inviting",
      "ember": "Burnished terracotta, confident",
      "grove": "Sage moss, warm and grounded",
      "plum": "Dusted violet, focused evening",
      "tide": "Cool slate, calm and focused"
    },
    "grid": {
      "ariaLabel": "Theme",
      "hint_one": "{{count}} palette · each has light & dark",
      "hint_other": "{{count}} palettes · each has light & dark",
      "selected": "{{name}}, selected",
      "title": "Themes"
    },
    "scheme": {
      "dark": "Dark",
      "light": "Light",
      "summary": "Light / Dark / System",
      "system": "System",
      "title": "Color scheme"
    }
  },
  "tree": {
    "actions": {
      "collapseAll": "Collapse all",
      "delete": "Delete",
      "duplicate": "Duplicate",
      "expandAll": "Expand all",
      "moveToRoot": "Move to Study Materials",
      "newFolder": "New folder",
      "rename": "Rename"
    },
    "defaults": {
      "folder": "folder",
      "item": "Item",
      "studyMaterial": "Study material",
      "untitledFolder": "Untitled folder"
    },
    "deleteDialog": {
      "description": "Delete \"{{name}}\"?",
      "folderTitle": "Delete folder",
      "materialTitle": "Delete study material",
      "prototypeDescription": "Delete \"{{name}}\" from this in-memory prototype?"
    },
    "errors": {
      "commandFailed": "Command failed",
      "connection": "Please check your connection and try again.",
      "deleteFailed": "Failed to delete",
      "deleteFolderFailed": "Failed to delete folder",
      "deleteMaterialFailed": "Failed to delete material",
      "duplicateFailed": "Failed to duplicate material",
      "invalidMove": "Invalid move",
      "loadFailed": "Failed to load study materials",
      "materialNotFound": "Material not found",
      "moveFailed": "Failed to move item",
      "nameEmpty": "Name cannot be empty",
      "refreshFailed": "Failed to refresh.",
      "renameFailed": "Failed to rename",
      "renameFolderFailed": "Failed to rename folder",
      "renameMaterialFailed": "Failed to rename material",
      "retry": "Retry",
      "retrying": "Retrying...",
      "unknownCommand": "Unknown command"
    },
    "header": {
      "collapseAllFolders": "Collapse all folders",
      "collapsePanel": "Collapse study materials",
      "dragToFolder": "Drag to a folder",
      "dropToRoot": "Drop to move to root",
      "expandAllFolders": "Expand all folders",
      "expandPanel": "Expand study materials",
      "newFolder": "New folder",
      "title": "Study Materials"
    },
    "lastAction": {
      "created": "Created {{name}}.",
      "deleted": "Deleted {{name}} from the local prototype.",
      "duplicated": "Duplicated {{name}}.",
      "moved": "Moved {{name}} to {{targetName}}.",
      "ready": "Ready to move study materials in memory.",
      "renamed": "Renamed {{previousName}} to {{nextName}}."
    },
    "row": {
      "actionsFor": "Actions for {{name}}",
      "dragHandle": "Drag to move",
      "itemName": "Item name"
    },
    "tree": {
      "ariaLabel": "Study materials",
      "emptyDescription": "Create a folder to begin.",
      "emptyDescriptionPrototype": "Create a folder to begin the in-memory prototype.",
      "emptyTitle": "No study materials",
      "loading": "Loading study materials",
      "updating": "Updating study materials"
    }
  },
  "viewer": {
    "caseStudy": {
      "alternativePerspectives": "Alternative Perspectives",
      "assumptions": "Assumptions",
      "conceptsFromSources": "Concepts From Your Sources",
      "confirmReset": "Confirm Reset",
      "fictionalNotice": "This scenario is fictional. Any supporting sources apply to the analysis.",
      "focus": "Focus:",
      "generatedFrom_one": "Generated from {{count}} notebook source.",
      "generatedFrom_other": "Generated from {{count}} notebook sources.",
      "hideAnalysis": "Hide Analysis",
      "hint": "Hint: {{hint}}",
      "keyPoints": "Key Points",
      "label": "Case Study",
      "noSampleAnalysis": "No sample analysis was included for this question.",
      "parseError": "This case study could not be read. Try reopening it or generating a new case.",
      "progressSaved": "Progress is saved on this device.",
      "question": "Question {{number}}",
      "relevantFacts": "Relevant Facts",
      "resetConfirm": "Clear all responses, checklist selections, and revealed analyses on this device?",
      "resetProgress": "Reset Progress",
      "responsePlaceholder": "Write your analysis before revealing the sample reasoning.",
      "revealAnalysis": "Reveal Analysis",
      "sampleReasoning": "Sample Reasoning",
      "scenarioAria": "Case scenario",
      "selfAssessment": "Self-Assessment Checklist",
      "storageResetError": "Reset failed on this device, but the session was cleared in memory.",
      "storageSaveError": "Progress could not be saved on this device. Your current session is kept in memory.",
      "tradeoffs": "Tradeoffs",
      "yourResponse": "Your Response"
    },
    "citations": {
      "aria": "Source citations",
      "title": "Citations"
    },
    "cloze": {
      "blankAnswer": "Blank {{number}}:",
      "blankAria": "Answer for blank {{number}}",
      "blankPlaceholder": "Blank {{number}}",
      "checkAnswer": "Check Answer",
      "correctAnswer": "Correct Answer",
      "correctAnswerLabel": "Correct Answer:",
      "incorrectAnswer": "Incorrect Answer",
      "missingWordPlaceholder": "Type the missing word…",
      "yourAnswer": "Your Answer"
    },
    "common": {
      "cancel": "Cancel",
      "close": "Close",
      "explain": "Explain",
      "generatedWithoutSources": "Generated without notebook sources.",
      "learningObjectives": "Learning Objectives",
      "loadingReferences": "Loading source references…",
      "next": "Next",
      "previous": "Previous",
      "referencesError": "Source references could not be loaded.",
      "retryReferences": "Retry References",
      "sourceReferenceUnavailable": "Source reference unavailable until loaded",
      "sourceUnavailable": "Source unavailable",
      "supportingSources": "Supporting Sources"
    },
    "flashcard": {
      "activeCard": "ACTIVE CARD",
      "bad": "Bad",
      "badContent": "Bad content",
      "cardAria": "Card {{number}}: {{type}}",
      "cardOf": "Card {{current}} of {{total}}",
      "clickToFlip": "Click to Flip",
      "clickToFlipBack": "Click to Flip Back",
      "defaultDeckTitle": "Flashcards Study Deck",
      "empty": "No flashcards available.",
      "explainBack": "The answer on the back reads:",
      "explainFront": "On the front it reads:",
      "explainInline": "\"On the front: '{{front}}'. On the back: '{{back}}'. Explain this topic in more detail.\"",
      "explainIntro": "\"I'm reviewing flashcards based on the source material and I'd like to expand my understanding of one of them.",
      "explainOutro": "Explain this topic in more detail.\"",
      "explainPrompt": "I'm reviewing flashcards based on the source material and I'd like to expand my understanding of one of them.\n\nOn the front it reads: \"{{front}}\"\n\nThe answer on the back reads: \"{{back}}\"\n\nExplain this topic in more detail.",
      "fullSentence": "Full sentence:",
      "good": "Good",
      "goodContent": "Good content",
      "nextCard": "Next Card",
      "position": "{{current}} / {{total}}",
      "previousCard": "Previous Card",
      "revealAnswer": "Click or press <kbd>{{key}}</kbd> to reveal answer",
      "searchCards": "Search cards...",
      "seeAnswer": "See answer",
      "showQuestion": "Show question",
      "sideBySide": "Side-by-Side",
      "singleFocus": "Single Focus",
      "sourceCount_one": "{{count}} source",
      "sourceCount_other": "{{count}} sources",
      "spaceToToggle": "Space to toggle",
      "staticExplainPreview": "Static Explain Prompt Preview",
      "staticExplainPrompt": "Static Explain Prompt",
      "types": {
        "answer": "Answer",
        "definition": "Definition",
        "fillInTheBlank": "Fill in the Blank",
        "question": "Question"
      },
      "viewSources_one": "View {{count}} source",
      "viewSources_other": "View {{count}} sources"
    },
    "header": {
      "exitFullscreen": "Exit Fullscreen",
      "exitFullscreenTitle": "Exit Fullscreen (Esc)",
      "fullscreenMode": "Fullscreen Mode",
      "returnToFullscreen": "Return to Fullscreen",
      "returnToStudio": "Return to Studio overview"
    },
    "kinds": {
      "case_study": "Case Study",
      "mind_map": "Mind Map",
      "practice_problems": "Practice Problems",
      "quiz": "Quiz",
      "roadmap": "Roadmap",
      "simple_flashcard": "Flashcards",
      "slides": "Slides",
      "study_guide": "Study Guide"
    },
    "kindsPlural": {
      "case_study": "Case Studies",
      "mind_map": "Mind Maps",
      "practice_problems": "Practice Problems",
      "quiz": "Quizzes",
      "roadmap": "Roadmaps",
      "simple_flashcard": "Flashcards",
      "slides": "Slides",
      "study_guide": "Study Guides"
    },
    "mindMap": {
      "center": "Center selected node",
      "collapse": "Collapse {{label}}",
      "empty": "This mind map has no connected nodes yet.",
      "expand": "Expand {{label}}",
      "hint": "Drag to pan · Scroll to zoom · Click a node to explore",
      "prompt": {
        "context": " from the study material \"{{title}}\"",
        "study": "I'm studying the mind-map concept \"{{label}}\"{{mindMapContext}}.\n\nPlease explain this concept in depth with practical examples, related ideas, and key insights I should remember."
      },
      "zoomIn": "Zoom in",
      "zoomOut": "Zoom out"
    },
    "practice": {
      "acceptableAlternatives": "Acceptable Alternatives",
      "areasForImprovement": "Areas for Improvement",
      "attemptAria": "Your attempt",
      "attemptPlaceholder": "Write your solution, calculations, or reasoning here...",
      "challengeLocked": "Challenge Mode: Solution Locked",
      "challengeNotice": "In Challenge mode, the reference solution unlocks once you evaluate your answer with AI.",
      "constraints": "Constraints",
      "difficulty": {
        "easy": "Warmup",
        "hard": "Challenge",
        "medium": "Standard"
      },
      "discussInChat": "Discuss in Chat",
      "discussTitle": "Discuss this problem in notebook chat",
      "evaluate": "Evaluate answer",
      "evaluateFailed": "Failed to evaluate answer",
      "evaluatedWithAi": "Evaluated with AI",
      "evaluating": "Evaluating with AI...",
      "evaluation": {
        "correct": "Correct",
        "needsRevision": "Needs Revision",
        "partiallyCorrect": "Partially Correct"
      },
      "exitDialog": {
        "description": "You have answers or evaluations in this session. If you leave now, your session progress will be lost.",
        "leave": "Leave Anyway",
        "stay": "Stay and Practice",
        "title": "Leave Practice Session?"
      },
      "explainStep": "Explain this step in Chat",
      "explainStepTitle": "Ask AI in chat to explain this step",
      "giveUp": "Give up and reveal solution",
      "givens": "Givens",
      "goToProblem": "Go to problem {{number}}",
      "hideSolution": "Hide Solution",
      "hint": "Hint {{number}}",
      "hints": "Hints",
      "hintsRevealed": "{{revealed}} of {{total}} hints revealed",
      "keyStrengths": "Key Strengths",
      "nextProblem": "Next problem",
      "parseError": "These practice problems could not be read. Try reopening them or generating a new set.",
      "previousProblem": "Previous problem",
      "problem": "Problem {{number}}",
      "problemOf": "Problem {{current}} of {{total}}",
      "prompts": {
        "constraints": "\nConstraints:\n{{values}}",
        "discuss": "I'm working on this practice problem and would like to discuss it:\n\n**Problem:**\n{{problem}}\n{{givens}}{{constraints}}\n\nCan you help me understand the core concepts and guide me on how to approach solving it?",
        "explainStep": "I'm reviewing the worked steps for this practice problem:\n\n**Problem:**\n{{problem}}\n\n**Step {{number}}: {{title}}**\n{{explanation}}\n\nCan you explain this step in more detail, clarify why this method was chosen, and walk me through the reasoning?",
        "givens": "\nGivens:\n{{values}}",
        "socratic": "I'm working on this practice problem and I'm feeling a bit stuck:\n\n**Problem:**\n{{problem}}\n\nWithout giving away the complete answer or worked steps, could you give me a Socratic hint or guiding question to help me figure out the next step myself?"
      },
      "reevaluate": "Re-evaluate",
      "referenceAnswer": "Reference Answer",
      "revealHint": "Reveal hint {{current}} of {{total}}",
      "revealSolution": "Reveal Full Solution",
      "selectModel": "Select a model to evaluate your answer.",
      "socraticButton": "Ask for Socratic Hint in Chat",
      "socraticTitle": "Ask AI in chat for a Socratic hint without revealing the solution",
      "solution": "Solution",
      "solutionHidden": "The solution is hidden to give you time to think and write your own attempt.",
      "sources": "Sources:",
      "step": "Step {{number}}: {{title}}",
      "stepSources": "Step Sources:",
      "verificationChecklist": "Verification Checklist",
      "workedSteps": "Worked Steps",
      "yourAttempt": "Your Attempt"
    },
    "quiz": {
      "answeredOf": "{{answered}} of {{total}} Answered",
      "backToResults": "Back to Results",
      "complete": "Quiz Complete",
      "correctStatus": "Your answer is correct.",
      "empty": "No quiz questions available.",
      "incorrectStatus": "Your answer is incorrect. The correct answer is {{answer}}",
      "options": {
        "correctAnswer": "Correct Answer",
        "yourAnswerCorrect": "Your Answer · Correct",
        "yourAnswerIncorrect": "Your Answer was incorrect"
      },
      "prompts": {
        "correctExplanation": "Correct Explanation: \"{{text}}\"",
        "explain": "I'm reviewing a quiz question and would like a deeper explanation of the concepts.\n\nQuestion: {{question}}\n{{selected}}\nCorrect Answer: \"{{answer}}\"\n{{explanation}}\n\nPlease explain why \"{{answer}}\" is correct{{incorrect}}, and break down the underlying concepts in detail.",
        "noAnswer": "No answer selected",
        "providedExplanation": "Provided Explanation: \"{{text}}\"",
        "selectedAnswer": "My Selected Answer: \"{{text}}\" ({{status}})",
        "statusCorrect": "Correct",
        "statusIncorrect": "Incorrect",
        "whyIncorrect": ", why \"{{text}}\" was incorrect"
      },
      "question": "Question {{number}}",
      "questionsAnswered": "Questions Answered",
      "retake": "Retake Quiz",
      "review": "Review Quiz",
      "scoreOf": "{{correct}} of {{total}} Correct",
      "selectNotice": "Selecting an answer checks it immediately. You cannot change it afterward.",
      "stats": {
        "correct": "Correct",
        "incorrect": "Incorrect",
        "unanswered": "Unanswered"
      },
      "submit": "Submit Quiz",
      "unanswered": {
        "description_one": "You still have {{count}} unanswered question. Would you like to review them before submitting?",
        "description_other": "You still have {{count}} unanswered questions. Would you like to review them before submitting?",
        "review": "Review Unanswered",
        "submitAnyway": "Submit Anyway",
        "title": "Unanswered Questions"
      },
      "unansweredNotice": "You left this question unanswered."
    },
    "roadmap": {
      "copied": "Copied",
      "copyFailed": "Copy failed",
      "copyTopic": "Copy {{title}}",
      "keyObjectives": "Key Objectives:",
      "phase": "Phase {{number}}",
      "prompt": {
        "context": " (\"{{title}}\")",
        "notAvailable": "N/A",
        "study": "I'm studying Phase {{number}}: \"{{title}}\" from my learning roadmap{{roadmapContext}}.\n\nPhase Description: {{description}}\n\nTopics covered in this phase:\n{{topics}}\n\nPlease act as my interactive AI tutor for this phase. Start by giving me a clear, high-level summary of what I'll master in this phase, and then ask me an initial concept question to check my understanding and kick off our study session!"
      },
      "studyInChat": "Study in chat"
    },
    "skeleton": {
      "kind": {
        "case_study": "Loading case study",
        "mind_map": "Loading mind map",
        "practice_problems": "Loading practice problems",
        "quiz": "Loading quiz",
        "roadmap": "Loading roadmap",
        "simple_flashcard": "Loading simple flashcard",
        "slides": "Loading slides",
        "study_guide": "Loading study guide"
      },
      "loadingDefault": "Loading study material",
      "loadingSr": "Loading study material…"
    },
    "slides": {
      "deckDesign": "Deck design: {{preset}}",
      "empty": "No slides in this deck yet.",
      "exportFailedToast": "Export failed",
      "exportPptx": "Export .pptx",
      "exportedToast": "PowerPoint exported",
      "goToSlide": "Go to slide {{number}}",
      "next": "Next slide",
      "position": "Slide {{current}} / {{total}}",
      "previewAlt": "Preview of slide {{number}}: {{title}}",
      "previewUnavailable": "Preview unavailable for this slide.",
      "previous": "Previous slide",
      "prompt": {
        "body": "Body: {{body}}",
        "content": "Content:\n{{lines}}",
        "keyPoints": "Key points:\n{{points}}",
        "notAvailable": "N/A",
        "study": "I'm studying slide {{number}} (\"{{title}}\", role: {{role}}) from my deck \"{{deck}}\".\n\nSubtitle: {{subtitle}}\n{{keyPoints}}{{body}}{{content}}\nPlease act as my tutor for this slide: summarize it clearly, then ask me one check-in question."
      },
      "speakerNotes": "Speaker notes: {{notes}}",
      "studyInChat": "Study this slide in chat",
      "unavailableAlt": "Slide {{number}} unavailable: {{title}}"
    },
    "studyGuide": {
      "commonMisconceptions": "Common Misconceptions",
      "contents": "Contents",
      "contentsAria": "Study guide contents",
      "detailed": "Detailed Guide",
      "generatedExamples": "Generated Examples",
      "keyConcepts": "Key Concepts",
      "parseError": "This study guide could not be read. Try reopening it or generating a new guide.",
      "revision": "Revision Sheet",
      "takeaways": "Takeaways"
    },
    "unsupportedMaterial": "Unsupported material type"
  }
}
